name: udacity-gen-ai
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - transformers
  - numpy
  - pandas
  - ipykernel
  - matplotlib
  - pip
  - pip:
    - scikit-learn
    - peft